spring:
  application:
    name: springcloud-zuul
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springcloud-web-admin-feign
